version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROCKET_DATABASES={neighborgoods_db={url=${DATABASE_URL}}}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
      - ROCKET_PORT=${ROCKET_PORT}
      - NODE_ID=${NODE_ID}
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5444:5432"
    command: -p 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=neighborgoods
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  cargo_cache:
  target_cache:
