[default.databases.neighborgoods_db]
url = "${DATABASE_URL}"

# Only `url` is required. These have sane defaults and are optional.
min_connections = 64
max_connections = 1024
connect_timeout = 5
idle_timeout = 120

[default]
limits = { file = "5 MiB" }