name: KICS Security Scan

on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master feature/* ]
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  kics-scan:
    name: KICS Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run KICS IaC Scan
        uses: checkmarx/kics-github-action@v2
        continue-on-error: true
        with:
          path: '.'
          output_formats: 'sarif,json'
          output_path: 'kics-results'
          verbose: true
          
      - name: Upload KICS Scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: kics-results/results.sarif

      - name: Debug - List output directory
        run: ls -R kics-results
