name: KICS Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  kics-scan:
    name: KICS Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      
      - name: Run KICS IaC Scan
        uses: checkmarx/kics-github-action@v1
        with:
          # Scan specific path for Docker and other IaC files
          path: '.'
          # Optional: Specify types of queries to run
          # For Docker scans, include 'dockerfile' at minimum
          type: 'dockerfile,docker-compose,kubernetes'
          # Generate output formats
          output_formats: 'json,sarif'
          # Output file name
          output_path: 'kics-results.sarif'
          # Optional: Exclude specific paths from scanning
          # exclude_paths: 'examples,docs'
          # Optional: Disable specific queries by their IDs
          # exclude_queries: '631a6892-7d42-44c0-a0ea-5417a6efd52eed221fcb-58d4-4a08-abba-1b2f2bc304f4'
          # Set platform type for the scan
          platform_type: 'github'
          
      - name: Upload KICS Scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()  # Run even if the previous step fails
        with:
          sarif_file: kics-results.sarif

      - name: Archive KICS results
        uses: actions/upload-artifact@v4
        if: always()  # Run even if the previous steps fail
        with:
          name: kics-results
          path: kics-results*
